# Background and foreground colors
background = #000000
foreground = #ffffff

# Standard colors
palette = 0=#000000
palette = 1=#F93459
palette = 2=#91a696
palette = 3=#E4E1D1
palette = 4=#8282a2
palette = 5=#A371AB
palette = 6=#A3DAF2
palette = 7=#F1F3F9

# Bright colors
palette = 8=#737373
palette = 9=#ff8aa0
palette = 10=#c3d0c6
palette = 11=#ffffff
palette = 12=#c0c0f5
palette = 13=#caa9cf
palette = 14=#f3fbfe
palette = 15=#ffffff
