background            #000000
foreground            #ffffff

# black
color0  #000000
color8  #737373

# red
color1  #F93459
color9  #ff8aa0

# green
color2  #91a696
color10 #c3d0c6

# yellow
color3  #E4E1D1
color11 #ffffff

# blue
color4  #8282a2
color12 #c0c0f5

# magenta
color5  #A371AB
color13 #caa9cf

#cyan
color6  #A3DAF2
color14 #f3fbfe

#white
color7  #F1F3F9
color15 #ffffff


